# Auto-deploy service definition for Render
# https://render.com/docs/deploy-nginx-python

services:
  - type: web
    name: optdesk
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn web_ui:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_KEY
        sync: false
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://optdesk.onrender.com
        sync: false